---
- name: Configure Workstation Environment
  hosts: localhost
  become: yes
  vars_prompt:
    - name: username
      prompt: "Enter Username: "
      private: no
  tasks:
    - name: Install System Packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - ca-certificates
        - software-properties-common

    - name: Install User Packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - vim
        - ncdu
        - htop
        - curl
        - wget
        - iputils-ping
        - unrar

    - name: Install Python 3 and pip
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
        - python3-venv
        - python3-setuptools

    - name: Install Docker and required packages
      block:
        - name: Add Docker GPG apt Key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker Repository
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu focal stable
            state: present

        - name: Update apt and install docker-ce
          apt:
            name: docker-ce
            state: latest
            update_cache: true

        - name: Add User to Docker Group
          user:
            name: "{{ username }}"
            groups: docker
            append: yes

    - name: Install VSCode
      block:
        - name: Download VSCode .deb Package
          get_url:
            url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
            dest: "/tmp/code.deb"
        
        - name: Install Visual Studio Code
          apt:
            deb: /tmp/code.deb
            state: present

        - name: Cleanup temporary .deb file
          file:
            path: /tmp/code.deb
            state: absent
        
        - name: Install Extensions
          become: yes
          become_user: "{{ username }}"
          command: code --install-extension {{ item }}
          with_items:
            - ms-vscode-remote.remote-containers
            - ms-vscode-remote.vscode-remote-extensionpack
    
    - name: Install Spotify
      block:
        - name: Add Spotify Repository
          apt_repository:
            repo: deb http://repository.spotify.com stable non-free
            state: present
        - name: Install Spotify
          apt:
            name: spotify-client
            state: present
